### ISSUE TITLE
Does this work in Unity 5.5. w/ Oculus? 

### ISSUE THREAD

**Issue by kyleroche** [Clodo76/vr-desktop-mirror#2]
I'm getting a plane w/ gray coloring but no replication of desktop. Steps I took: 
- Oculus Camera Mount to scene (remove default camera)
- vr-desktop prefab to scene (left in default location)
- launch
- hit left ctrl button (surface renders fine but w/out texture)

**Comment by simpleshadow** [comment]
@kyleroche Just got it running with Oculus in Unity 2017, no changes needed. 👍

**Comment by amack2u** [comment]
@simpleshadow any chance on getting this working with oculus touch controllers?
